### ISSUE TITLE
scrolling down is a bit jank

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/website-v2#13]
### Describe the bug

![image](https://github.com/taikoxyz/website-v2/assets/13951458/5cd0871a-319b-4248-a2b2-f191867ea85a)

when you visit the website at http://taiko.xyz you will see that the cards slide behind the next area, instead if should "disappear" through the top, instead of being "sticky".

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by xlzy905** [comment]
Does it mean that there is no need for a sticky and the page should scroll down normally
