### ISSUE TITLE
MAINNET Stakely Faucet - Taiko

### ISSUE THREAD

**Issue by Josepdal** [taikoxyz/website-v2#138]
### Title of your project

Stakely Faucet - Taiko

### Short (1-2 sentence) description of your project

Did you run out of ETH to pay for gas in Taiko? Use our faucet and receive enough to make several transactions in a matter of seconds.

### Link to your project

https://stakely.io/en/faucet/taiko-eth

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://taikoscan.io/address/0x0e79065b5f11b5bd1e62b935a600976fff3754b9

### Upload a quality logo to your project

![stakely-logo](https://github.com/taikoxyz/website-v2/assets/11841883/60ea5790-1bf3-4784-8d26-7799255abd16)

**Comment by dimuniq** [comment]
Cool! But the wait is long... I've been waiting for several minutes, I hope the ETH will come. =)
![1](https://github.com/user-attachments/assets/c17a7bf6-8450-4ac3-a0eb-afa4422324b0)
