### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/website-v2#16]
### Describe the feature request

some people requested dark mode. i'm not sure if we can do it, but here is the issue for tracking.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by forbesus** [comment]
I am available this work?

**Comment by forbesus** [comment]
@d1onys1us do you still need this work?

**Comment by forbesus** [comment]
Hello @d1onys1us I wanna resolve this issue

**Comment by d1onys1us** [comment]
I believe this is no longer a high priority. I will close for now, and let @bennettyong re-open if it is deemed necessary. Thank you!
