### ISSUE TITLE
WAGASA NFT Collection

### ISSUE THREAD

**Issue by R0cketTeam** [taikoxyz/website-v2#208]
### Title of your project

WAGASA

### Short (1-2 sentence) description of your project

WAGASA is a limited series collection of 39,393 generative artworks, encapsulating themes of nihilism, inherent cruelty, and greed - echoing our trivial existence in an uncaring universe.

### Link to your project

https://www.wagasa.xyz/

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://taikoscan.io/address/0xb5983E867B9053E5F542BcbE157d295d3C3AbF18#code

### Upload a quality logo to your project

![wasagaLogoTransp512](https://github.com/user-attachments/assets/d93ab579-2cd0-49c1-9cdf-238a7907e8bf)

**Comment by R0cketTeam** [comment]
Hello. You marked as completed but we couldnt find the project on Ecosystem page. If need additional info we can provide.

**Comment by swarna1101** [comment]
check now pls

**Comment by R0cketTeam** [comment]
Thanks man.
