### ISSUE TITLE
Blog Page - Filters Don't Work and Formatting Suggestions

### ISSUE THREAD

**Issue by ablankstory** [taikoxyz/website-v2#21]
### Describe the bug

Description of the bug here.

The Filter options on the Blog page (https://taiko.xyz/blog) don't work properly. Additionally, the Filters and Buttons (at top) could probably do with switching to Taiko pink (#E81899).

### Steps to reproduce

Steps to reproduce here.

1. Use the date filter to switch to "For the last month". You'll still see all posts, including 09 Dec 2022.

2. Use the Topic filter to switch to "The Rollup Coaster". No articles appear even though ALL shows "ZK-Roller-Coaster #9".

3. Additionally, I think the buttons at the top could look better as Taiko pink, with white font inside. Example:
<img width="722" alt="Screenshot 2024-03-30 at 5 37 41 PM" src="https://github.com/taikoxyz/website-v2/assets/104391159/f88e52a0-263d-46ea-836d-9fac1d92dc56">

Maybe adjusting the colors of the filters too to include Taiko pink as well. Right now, there are just a lot of different shades of white. But this could all be personal preference.

<img width="290" alt="Screenshot 2024-03-30 at 5 43 00 PM" src="https://github.com/taikoxyz/website-v2/assets/104391159/e9c02aaa-beac-4695-84ab-777d32d53f16">

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by bennettyong** [comment]
fixed as of #22
