### ISSUE TITLE
Shards

### ISSUE THREAD

**Issue by azizshards** [taikoxyz/website-v2#47]
### Title of your project

Shards

### Short (1-2 sentence) description of your project

Shards is a free-to-use SDK designed to enhance in-game engagement and revenue for game studios. It allows users to create, fractionalize, and trade in-game guilds, providing a cutting-edge solution for game economy management. Engine-agnostic and easy to integrate, Shards supports seamless implementation across various game platforms.  Key features include smart contract-enforced revenue sharing, which streamlines gameplay, monetization, and community building. By leveraging Shards, game studios can offer additional earning opportunities to both players and non-players, fostering increased user engagement and liquidity flow. The platform also aims to bootstrap the aggregate Total Value Locked (TVL) within the game ecosystem, with initial campaigns already generating significant trading volume.  Shards represents a technologically advanced toolset for modern game development, combining innovation in blockchain technology with practical applications in the gaming industry.

### Link to your project

https://shards.tech/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

The project supports Taiko blockchain, doesn't need to be directly connected to the blockchain.

### Upload a quality logo to your project

![Shards_Icon](https://github.com/taikoxyz/website-v2/assets/170733528/ed015c0c-9fe6-4298-8b46-12439146fb2d)

**Comment by azizshards** [comment]
Hi there.

Why's this ticket closed?

пн, 27 мая 2024 г., 19:00 swarna1101 ***@***.***>:

**Comment by swarna1101** [comment]
pls deploy on mainnet

**Comment by azizshards** [comment]
Hello there,

We are Taiko compatible and our suite doesn't need to be on chain but
rather connects to the game data and allows on chain interaction. Welcome
to ask about our partnership from Pigi and/or Alex.

вт, 28 мая 2024 г., 00:30 swarna1101 ***@***.***>:
