### ISSUE TITLE
Ritsu Exchange

### ISSUE THREAD

**Issue by 0xnakato** [taikoxyz/website-v2#52]
### Title of your project

Ritsu Exchange

### Short (1-2 sentence) description of your project

Ritsu is a based decentralized exchange on Taiko featuring hyper efficiency and user friendly experience powered by the Rhythm AMM.

### Link to your project

http://ritsu.xyz/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Plan for mainnet

### Upload a quality logo to your project

![r_logo9](https://github.com/taikoxyz/website-v2/assets/94997114/1944ffec-c13f-4492-a114-5f57cd1f898b)

**Comment by swarna1101** [comment]
fill the form again, when you are live on Taiko mainnet
