### ISSUE TITLE
Add TaikoSwap to list

### ISSUE THREAD

**Issue by xIceyyx** [taikoxyz/website-v2#54]
### Title of your project

TaikoSwap

### Short (1-2 sentence) description of your project

Taiko's original decentralized exchange 🥁

### Link to your project

https://www.swaptko.xyz/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

We will be deploying on mainnet as soon as its live

### Upload a quality logo to your project

![tswappfp](https://github.com/taikoxyz/website-v2/assets/77045488/c9a349b2-d247-46a3-9aef-970202418acb)

**Comment by swarna1101** [comment]
pls fill the form again when you are live on taiko mainnet

**Comment by xIceyyx** [comment]
we're live

**Comment by xIceyyx** [comment]
We're live can you please add it? https://www.swaptko.xyz/
