### ISSUE TITLE
MakiSwap submission

### ISSUE THREAD

**Issue by GioeleChain** [taikoxyz/website-v2#77]
### Title of your project

Maki Swap

### Short (1-2 sentence) description of your project

Leading DEX on Taiko. Providing advanced economy for liquidity pool providers, stakers and users.

### Link to your project

https://www.makiswap.io/

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Live

### Upload a quality logo to your project

![Screenshot 2024-05-27 174709](https://github.com/taikoxyz/website-v2/assets/143438656/c3b0f4f3-b4a3-4afc-8da6-975b4cec0cb6) Live on Mainnet 
![Group](https://github.com/taikoxyz/website-v2/assets/143438656/d4cc5c92-bcc2-477a-86ab-fa53d12f3e6c)
Logo

**Comment by swarna1101** [comment]
done
