### ISSUE TITLE
EVM Warfare

### ISSUE THREAD

**Issue by harshitsiwach** [taikoxyz/website-v2#80]
### Title of your project

Skill based Gambling Third Person Shooter Game built in Unreal Engine 5

### Short (1-2 sentence) description of your project

We are a Third person shooter gaming project building on Unreal Engine which is compatible with all EVM Chains. 

### Link to your project

https://evmwarfare.com/

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://mega.nz/file/VKk0UbZI#9rKLSaOkD3jXOatuen82E6eaAPFw1yNe2kX2LwJc1R0

### Upload a quality logo to your project

![EVMLogo600x600](https://github.com/taikoxyz/website-v2/assets/37680927/811dc013-bcb0-4c9d-a038-d00954b3ac8d)

**Comment by swarna1101** [comment]
done
