### ISSUE TITLE
TaikoSwap (vanilla UniswapV2 fork)

### ISSUE THREAD

**Issue by CryptoPhantom777** [taikoxyz/website-v2#85]
### Title of your project

TaikoSwap

### Short (1-2 sentence) description of your project

TaikoSwap is a 1:1 fork of UniswapV2 to let degens trade memecoins the OG way!

### Link to your project

https://tkoswap.xyz

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://x.com/GeckoTerminal/status/1795102794266902756
https://x.com/DefiLlama/status/1795154113505656946
https://taikoscan.network/address/0x278E9cbe8839a8B634bb214b58207BE3743195aC/contract/167000/code

### Upload a quality logo to your project

![logo](https://github.com/taikoxyz/website-v2/assets/166310737/1602fc01-5557-4272-a1e1-2a5362158929)

**Comment by DNALFIN** [comment]
Taikoswap is 2nd perfect dex swap made by safe team, 35k mcap is seem big undervalued
