### ISSUE TITLE
Particle Network

### ISSUE THREAD

**Issue by TABASCOatw** [taikoxyz/website-v2#86]
### Title of your project

Particle Network

### Short (1-2 sentence) description of your project

Particle Network is the Modular L1 powering Chain Abstraction, solving Web3's issues of liquidity and user fragmentation.

### Link to your project

https://particle.network

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://blog.particle.network/account-abstraction-social-login-feature-taiko, https://core-demo.particle.network

### Upload a quality logo to your project

![image](https://github.com/taikoxyz/website-v2/assets/84655644/42fef835-7ef1-4f7d-8de5-fc8c1ac15cdb)

**Comment by swarna1101** [comment]
its live now
