### ISSUE TITLE
add ImaginAIryNFTs to Taiko Mainnet ecosystem

### ISSUE THREAD

**Issue by L-KH** [taikoxyz/website-v2#87]
### Title of your project

ImaginAIryNFTs

### Short (1-2 sentence) description of your project

Unleash creativity with AI-generated art. Mint unique NFTs from your AI-dreamed designs. Your Prompt, Your Art, Your NFT!

### Link to your project

https://www.imaginairynfts.com/

### Live on Mainnet

Yes (default)

### If your project is live on Mainnet, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://taikoscan.io/address/0xb99e5534d42500eb1d5820fba3bb8416ccb76396#code

### Upload a quality logo to your project

![ImaginAIry_NFTs](https://github.com/taikoxyz/website-v2/assets/12660772/dc9e811a-9a0b-4c0f-aff3-d69ebbcd20ae)

**Comment by swarna1101** [comment]
done
